version: '2'
networks:
  app_net:
    driver: bridge
services:
  mysql:
    image: mysql:5.7
    networks:
      - app_net
    hostname: mysql
    container_name: mysql
    restart: always
    volumes:
    - ./data/mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=123456789
  nginx-php-fpm:
    image: richarvey/nginx-php-fpm
    networks:
      - app_net
    hostname: nginx-php
    container_name: nginx-php
    restart: always
    ports:
    - "88:80"
    - "89:8080"
    volumes:
    - ./data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    - ./data/nginx/conf/conf.d:/etc/nginx/sites-enabled
    - ./data/nginx/logs:/var/log/nginx
    - ./data/nginx/htdocs:/var/www/html
  svn:
    image: garethflowers/svn-server
    networks:
      - app_net
    hostname: svn
    container_name: svn
    restart: always
    ports:
    - 8888:3690
    volumes:
    - ./data/svn:/var/opt/svn
    # docker exec -it svn svnadmin create new-repo
  gogs:
    image: gogs/gogs
    networks:
      - app_net
    hostname: gogs
    container_name: gogs
    restart: always
    ports:
    - "10022:22"
    - "888:3000"
    volumes:
    - ./data/gogs:/data
  nexus:
    image: sonatype/nexus
    networks:
      - app_net
    hostname: nexus
    container_name: nexus
    restart: always
    ports:
    - 889:8081
    volumes:
    # chown -R 200:200 ./data/nexus
    - ./data/nexus:/sonatype-work
